services:
  - type: web
    name: optigenix
    env: python
    buildCommand: pip install -r requirements.txt && pip install psutil==5.9.0 polyline==2.0.0
    startCommand: gunicorn app:app --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --timeout 300
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: SECRET_KEY
        generateValue: true
