services:
  - type: web
    name: optigenix
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --timeout 300 wsgi:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: SECRET_KEY
        generateValue: true
