services:
  - type: web
    name: optigenix
    env: python
    region: ohio # Choose a region close to your users
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 wsgi:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: SECRET_KEY
        generateValue: true








        - "**/*.py"        - requirements.txt      paths:    buildFilter:    healthCheckPath: /        value: 3.9.16      - key: PYTHON_VERSION